# Generated by Django 3.0.7 on 2020-06-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='create_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_activate',
            new_name='is_active',
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('askFrom', 'askTo')},
        ),
    ]
